import type { NextPage } from "next";
import Head from "next/head";
import React, { FormEvent, SyntheticEvent, useState } from "react";
import { useMutation, useQuery } from "../../convex/_generated";
import AddTeamForm from "../../components/admin/AddTeamForm";
import StartQuizBtn from "../../components/admin/StartQuizBtn";

// TODO: protect with basic auth middleware
// https://stackoverflow.com/questions/64316886/how-do-i-add-basic-authentication-to-nextjs-node-server

// If hasQuizStarted
//   - Show slides and teams (points/directs etc)
// Else
//   - Show add team form and start quiz button

const Admin: NextPage = () => {
  const quizStarted = useQuery("quizStarted");

  return (
    <div>
      <Head>
        <title>Admin | ExQuiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {quizStarted ? (
        <div>quiz started</div>
      ) : (
        <div>
          <AddTeamForm />
          <StartQuizBtn />
        </div>
      )}
    </div>
  );
};

export default Admin;
