import type { NextPage } from "next";
import Head from "next/head";
import React, { FormEvent, useState } from "react";
import { useMutation } from "../../convex/_generated";

// TODO: protect with basic auth middleware
// https://stackoverflow.com/questions/64316886/how-do-i-add-basic-authentication-to-nextjs-node-server

const Admin: NextPage = () => {
  const [tnumber, setTnumber] = useState(1);
  const [name, setName] = useState("");
  const [error, setError] = useState("");
  const createTeam = useMutation("createTeam");

  return (
    <div>
      <Head>
        <title>Admin | ExQuiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <form
          onSubmit={async (e) => {
            e.preventDefault();
            setError("");

            if (tnumber < 1) {
              setError("Team number must be > 0");
              return;
            }

            if (name === "") {
              setError(
                "Team name cannot be empty, eg: 'Vinayak Pachnanda, Angad Singh'"
              );
              return;
            }

            setTnumber(1); // reset text entry box
            setName("");

            await createTeam(tnumber, name);
            setError("Team Created");
          }}
          className="p-10 flex flex-col gap-y-3"
        >
          <div className="flex items-center gap-x-5">
            <label htmlFor="tnumber">Team Number</label>
            <input
              name="tnumber"
              type="number"
              value={tnumber}
              onChange={(e) => setTnumber(Number(e.target.value))}
            />
          </div>
          <div className="flex items-center gap-x-5">
            <label htmlFor="name">Team Name</label>
            <input
              name="name"
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
          </div>
          <div className="text-red-500">{error}</div>
          <div>
            <button
              type="submit"
              className="bg-exun uppercase font-bold text-white p-3 rounded"
            >
              Create
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Admin;
