import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Rules from "../components/onboarding/Rules";

const Home: NextPage = () => {
  // show teams here

  return (
    <div>
      <Head>
        <title>ExQuiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen w-screen grid grid-cols-2 p-[50px] gap-x-[50px] text-slate-700">
        <Rules />
        <div>teams here</div>
      </div>
    </div>
  );
};

export default Home;
