import type { NextPage } from "next";
import Head from "next/head";
import Rules from "../components/onboarding/Rules";
import { useQuery } from "../convex/_generated";
import TeamCard from "../components/onboarding/TeamCard";
import Onboarding from "../components/onboarding/Onboarding";

const Home: NextPage = () => {
  const teams = useQuery("allTeams") || [];
  const quizStarted = useQuery("quizStarted");

  return (
    <div>
      <Head>
        <title>ExQuiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {quizStarted?.value === true ? <div>started</div> : <Onboarding />}
    </div>
  );
};

export default Home;
